server:
  port: 8002

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://127.0.0.1:6379"
          timeout: 10000
          connectTimeout: 10000
          connectionPoolSize: 64
          connectionMinimumIdleSize: 24


# 添加 MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag  # 逻辑删除字段
      logic-delete-value: 1        # 逻辑删除值
      logic-not-delete-value: 0    # 逻辑未删除值

# 开启调试日志
logging:
  level:
    org.getoffer.shortlink.admin: DEBUG
    com.baomidou.mybatisplus: DEBUG


